### PR TITLE
Fix several issues found by pylint

### PR DESCRIPTION
**Pull request by dalgaaf**
Includes fixes for:
- bad indentation
- wrong continued indentation
- old-style-class
- bad and trailing whitespaces
- import only what's needed
- unused imports
- unused variables
- superfluous-parens
- multiple-statements in one line
- too long lines

Also included:
- use UNIX instead of Windows line endings
- add .gitignore

### CODE REVIEW

**Comment by dalgaaf** [comment]
@alfredodeza : finally found some time to update this pull request. fixed the issues in aging/runtests.py

**Comment by dalgaaf** [comment]
@alfredodeza : ready for merge?

**Comment by alfredodeza** [comment]
This is a *lot* to digest in one PR. It looks ok to me, couldn't catch anything but, it is so much that I fear my review may not be completely thorough.

I would say it looks good to get merged. I would encourage a smaller PR next time around though :)

**Comment by dalgaaf** [comment]
Hm, sorry ... next time I split it up (put them together because they all falled out of pylint). Do you add the review tag and merge it?

**Comment by dalgaaf** [comment]
@alfredodeza ready for merge? Would like to cross this on off my list.

**Comment by dalgaaf** [comment]
thx

**Pull request merged**
